export const ENDPOINTS = {
    SIGNUP: '/auth/registration',
    ACTIVATE_PROFILE: '/auth/activate/:uuid',
    SIGNIN: '/auth/login',
    PROFILE: '/users/me',
    HOREKA_REQUESTS: '/horeca/requests',
    HOREKA_FAVOURITES: '/horeca/favourites',
    HOREKA_REQUESTS_TEMPLATES: '/horeca/requests/templates',
    HOREKA_REQUEST: '/horeca/requests/:id',
    HOREKA_REQUESTS_FOR_PROVIDER: '/provider/requests/income',
    HOREKA_REQUESTS_FOR_PROVIDER_STATUS: '/provider/requests/income/status',
    PROVIDER_REQUESTS: '/provider/requests',
    CHATS: '/chats',
    CHAT: '/chats/:id',
    CHAT_MESSAGES: '/messages',
    HOREKA_APPROVE_PROVIDER_REQUEST: '/horeca/requests/approve',
}
