services:
    horeca_api:
        container_name: horeca_api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ~/docker-volumes/horeca_api-uploads:/app/uploads
            - ~/docker-volumes/horeca_api-logs:/app/logs
        env_file: '.env'
        ports:
            - '127.0.0.1:3001:3001'
            - '127.0.0.1:4001:4001'
        restart: always
        depends_on:
            - horeca_ps
        networks:
            - horeca_api_network

    horeca_ps:
        container_name: horeca_ps
        image: postgres:14
        restart: always
        volumes:
            - ./db_scripts:/docker-entrypoint-initdb.d
            - ~/docker-volumes/horeca_postgres-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=horeca
            - POSTGRES_PASSWORD=horeca
            - POSTGRES_DB=horeca
        networks:
            - horeca_api_network
    horeca_redis:
        image: redis:7
        container_name: horeca_redis
        ports:
            - "6379:6379"
        networks:
            - horeca_api_network
        
volumes:
    horeca_api-uploads:
    horeca_postgres-data:

networks:
  horeca_api_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450