services:
    horeca_api:
        container_name: horeca_api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ~/docker-volumes/horeca_api-uploads:/app/uploads
            - ~/docker-volumes/horeca_api-logs:/app/logs
        env_file: '.env'
        environment:
            - DATABASE_URL=postgresql://horeca:horeca@horeca_ps:5432/horeca?schema=public
        ports:
            - '127.0.0.1:3001:3001'
            - '127.0.0.1:4001:4001'
        restart: unless-stopped
        depends_on:
            horeca_ps:
                condition: service_healthy
            horeca_redis:
                condition: service_healthy
        networks:
            - horeca_api_network

    horeca_ps:
        container_name: horeca_ps
        image: postgres:14
        restart: unless-stopped
        volumes:
            - ./db_scripts:/docker-entrypoint-initdb.d
            - ~/docker-volumes/horeca_postgres-data:/var/lib/postgresql/data
        ports:
            - '127.0.0.1:5435:5432'
        environment:
            - POSTGRES_USER=horeca
            - POSTGRES_PASSWORD=horeca
            - POSTGRES_DB=horeca
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U horeca -d horeca"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - horeca_api_network
    horeca_redis:
        image: redis:7
        container_name: horeca_redis
        ports:
            - "127.0.0.1:6380:6379"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5
        networks:
            - horeca_api_network
        
volumes:
    horeca_api-logs:
    horeca_api-uploads:
    horeca_postgres-data:

networks:
  horeca_api_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450