services:
  db:
    image: postgres:14
    restart: always
    container_name: horeca-tests-prisma
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: horeca-tests