services:
    horeca_api:
        container_name: horeca_api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ~/docker-volumes/horeca_api-uploads:/app/uploads
        env_file: '.env'
        ports:
            - '3001:3001'
            - '4001:4001'
        depends_on:
            - horeca_ps

    horeca_ps:
        container_name: horeca_ps
        image: postgres:14
        restart: always
        volumes:
            - ./db_scripts:/docker-entrypoint-initdb.d
            - ~/docker-volumes/horeca_postgres-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=horeca
            - POSTGRES_PASSWORD=horeca
            - POSTGRES_DB=horeca
volumes:
    horeca_api-uploads:
    horeca_postgres-data:
