export enum ErrorCodes {
    AUTH_FAIL = 'AUTH_FAIL', // ошибка авторизации
    ITEM_NOT_FOUND = 'ITEM_NOT_FOUND', // элемент не найден
    MAIL_IS_BUSY = 'MAIL_IS_BUSY', // почта занята
    PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR', // ошибка изменения пароля

    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USER_DOES_NOT_EXISTS = 'USER_DOES_NOT_EXISTS',

    GDPR_IS_NOT_APPROVED = 'GDPR_IS_NOT_APPROVED',

    UPLOAD_NOT_FOUND = 'UPLOAD_NOT_FOUND',
    ACTIVATION_LINK_ERROR = 'ACTIVATION_LINK_ERROR',

    INVALID_QUERY_STRING = 'INVALID_QUERY_STRING',

    FORBIDDEN_ACTION = 'FORBIDDEN_ACTION',

    TEMPLATE_DOES_NOT_EXISTS = 'TEMPLATE_DOES_NOT_EXISTS',
}
