export enum NotificationEvents {
    REVIEW = 'REVIEW',
    REVIEW_REMINDER = 'REVIEW_REMINDER',

    PROVIDER_ADDED_TO_FAVOURITES = 'PROVIDER_ADDED_IN_FAVOURITES',
    PROVIDER_DELETED_FROM_FAVOURITES = 'PROVIDER_DELETED_FROM_FAVOURITES',

    PROVIDER_REQUEST_CREATED = 'PROVIDER_REQUEST_CREATED',
    PROVIDER_REQUEST_STATUS_CHANGED = 'PROVIDER_REQUEST_STATUS_CHANGED',
}

export enum ChatEvents {
    MESSAGE = 'message',
}
