export enum NotificationEvents {
    REVIEW = 'REVIEW',
    REVIEW_REMINDER = 'REVIEW_REMINDER',
    PROVIDER_REQUEST = 'PROVIDER_REQUEST',
    PROVIDER_REQUEST_CANCELED = 'PROVIDER_REQUEST_CANCELED',
    HORECA_REQUEST_CANCELED = 'HORECA_REQUEST_CANCELED',
}

export enum ChatEvents {
    MESSAGE = 'message',
}
