export enum NotificationEvents {
    REVIEW = 'REVIEW',
    REVIEW_REMINDER = 'REVIEW_REMINDER',
    NEW_MESSAGE = 'NEW_MESSAGE',
    NEW_PROVIDER_REQUEST = 'NEW_PROVIDER_REQUEST',
    NEW_HORECA_REQUEST = 'NEW_HORECA_REQUEST',
    PROVIDER_APPROVED = 'PROVIDER_APPROVED',
}

export enum ChatEvents {
    MESSAGE = 'message',
}
