export enum Categories {
    alcoholicDrinks = 'alcoholicDrinks',
    grocerySpicesSeasonings = 'grocerySpicesSeasonings',
    softDrinks = 'softDrinks',
    readyMeals = 'readyMeals',
    stationery = 'stationery',
    confectionery = 'confectionery',
    cannedFoods = 'cannedFoods',
    dairyProducts = 'dairyProducts',
    iceCream = 'iceCream',
    meat = 'meat',
    lowAlcoholDrinks = 'lowAlcoholDrinks',
    semiFinishedProducts = 'semiFinishedProducts',
    dishes = 'dishes',
    cashDesk = 'cashDesk',
    instantFoods = 'instantFoods',
    fish = 'fish',
    fruitsAndVegetables = 'fruitsAndVegetables',
    cleaningProducts = 'cleaningProducts',
    bakeryProducts = 'bakeryProducts',
    teeAndCoffee = 'teeAndCoffee',
}
