name: Deploy to Dev

on:
    push:
        branches: ['develop']

jobs:
    deploy:
        runs-on: [self-hosted, horeca-dev]
        environment: development
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Create .env file
              run: echo "${{ secrets.DEV_ENV_FILE }}" > .env
            - name: run in docker
              run: docker compose up --build -d
